INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Notebook', 'Dell I7', '6000');
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Teclado Redragon', 'Mecânico RGB', '600');
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Mouse Logitech', 'Sem Fio', '300');